// <auto-generated />
using System;
using Forum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forum.DAL.Migrations
{
    [DbContext(typeof(ForumContext))]
    [Migration("20230226111840_UpdateReactionAndRole")]
    partial class UpdateReactionAndRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forum.DAL.Entity.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Downvotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Forum.DAL.Entity.PostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Downvotes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReactionTypeId");

                    b.ToTable("Reaction");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReactionType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74373a5e-ef21-4b3c-8709-43ae482d7248"),
                            Abrv = "upvote",
                            DateCreated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6661),
                            DateUpdated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6661),
                            Name = "Upvote"
                        },
                        new
                        {
                            Id = new Guid("76822a43-7c7e-4bb6-80a9-888542bf185a"),
                            Abrv = "Downvote",
                            DateCreated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6673),
                            DateUpdated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6673),
                            Name = "Downvote"
                        });
                });

            modelBuilder.Entity("Forum.DAL.Entity.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b6ac206-c7cd-49fb-9d3f-548063ceb469"),
                            Abrv = "admin",
                            DateCreated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6587),
                            DateUpdated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6588),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("21dc2fcd-17c3-49cf-862e-cd6ffbe9fd03"),
                            Abrv = "super-admin",
                            DateCreated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6590),
                            DateUpdated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6590),
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = new Guid("b3775d8e-62d2-4f82-8649-5192d90c804b"),
                            Abrv = "user",
                            DateCreated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6591),
                            DateUpdated = new DateTime(2023, 2, 26, 11, 18, 39, 526, DateTimeKind.Utc).AddTicks(6592),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Forum.DAL.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.CommentEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.PostEntity", "Post")
                        .WithMany("Comment")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forum.DAL.Entity.UserEntity", "User")
                        .WithMany("Comment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.PostEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.UserEntity", "User")
                        .WithMany("Post")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.ReactionTypeEntity", "ReactionType")
                        .WithMany("Reaction")
                        .HasForeignKey("ReactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReactionType");
                });

            modelBuilder.Entity("Forum.DAL.Entity.UserEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.RoleEntity", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Forum.DAL.Entity.PostEntity", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionTypeEntity", b =>
                {
                    b.Navigation("Reaction");
                });

            modelBuilder.Entity("Forum.DAL.Entity.RoleEntity", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.UserEntity", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
