// <auto-generated />
using System;
using Forum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forum.DAL.Migrations
{
    [DbContext(typeof(ForumContext))]
    [Migration("20230226193247_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forum.DAL.Entity.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Downvotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Forum.DAL.Entity.PostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Downvotes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReactionTypeId");

                    b.ToTable("Reaction");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReactionType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35814a70-dc96-4942-a911-d81e921b50ea"),
                            Abrv = "upvote",
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9528),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9529),
                            Name = "Upvote"
                        },
                        new
                        {
                            Id = new Guid("2d5de9c7-99c5-4b93-8e9a-68aca3202af7"),
                            Abrv = "Downvote",
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9531),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9532),
                            Name = "Downvote"
                        });
                });

            modelBuilder.Entity("Forum.DAL.Entity.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18812906-8a79-47a8-905e-d5ab1c98298a"),
                            Abrv = "admin",
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9450),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9451),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("2ef7989e-5cf9-4553-b2c6-31f394299e54"),
                            Abrv = "super-admin",
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9453),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9454),
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Abrv = "user",
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9456),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9456),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Forum.DAL.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69dca97c-b245-4c9a-a306-89a875452e6a"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9568),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9569),
                            Email = "danijel.jakovac0@gmail.com",
                            FirstName = "Danijel - 0",
                            LastName = "Jakovac - 0",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel0"
                        },
                        new
                        {
                            Id = new Guid("c98856dc-2601-4c3b-882b-fdab27863272"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9595),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9595),
                            Email = "danijel.jakovac1@gmail.com",
                            FirstName = "Danijel - 1",
                            LastName = "Jakovac - 1",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel1"
                        },
                        new
                        {
                            Id = new Guid("c3bcad5c-3bc5-4626-90da-a2ae2b2b8de6"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9602),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9603),
                            Email = "danijel.jakovac2@gmail.com",
                            FirstName = "Danijel - 2",
                            LastName = "Jakovac - 2",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel2"
                        },
                        new
                        {
                            Id = new Guid("49763c99-86c2-4d7f-9cdb-be01cd0638a4"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9609),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9609),
                            Email = "danijel.jakovac3@gmail.com",
                            FirstName = "Danijel - 3",
                            LastName = "Jakovac - 3",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel3"
                        },
                        new
                        {
                            Id = new Guid("44061739-451d-4ce9-b2ab-d2f6468b9ab2"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9616),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9616),
                            Email = "danijel.jakovac4@gmail.com",
                            FirstName = "Danijel - 4",
                            LastName = "Jakovac - 4",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel4"
                        },
                        new
                        {
                            Id = new Guid("41f43c69-b2b6-4ee6-891a-b5120358b6b4"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9623),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9623),
                            Email = "danijel.jakovac5@gmail.com",
                            FirstName = "Danijel - 5",
                            LastName = "Jakovac - 5",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel5"
                        },
                        new
                        {
                            Id = new Guid("3c2fa294-0ef1-46b2-85a2-15501a0751c5"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9660),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9660),
                            Email = "danijel.jakovac6@gmail.com",
                            FirstName = "Danijel - 6",
                            LastName = "Jakovac - 6",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel6"
                        },
                        new
                        {
                            Id = new Guid("8b775a51-ecb3-44e8-9817-c4b7ed1f45e4"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9667),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9667),
                            Email = "danijel.jakovac7@gmail.com",
                            FirstName = "Danijel - 7",
                            LastName = "Jakovac - 7",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel7"
                        },
                        new
                        {
                            Id = new Guid("013837bb-026c-4384-9f45-4c405fc177a2"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9676),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9676),
                            Email = "danijel.jakovac8@gmail.com",
                            FirstName = "Danijel - 8",
                            LastName = "Jakovac - 8",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel8"
                        },
                        new
                        {
                            Id = new Guid("cc9dbd24-d0c7-4574-8415-e7494ca7bd7d"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9683),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9684),
                            Email = "danijel.jakovac9@gmail.com",
                            FirstName = "Danijel - 9",
                            LastName = "Jakovac - 9",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel9"
                        },
                        new
                        {
                            Id = new Guid("2f6b5645-0070-466f-9ad2-1875d2a7db32"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9689),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9690),
                            Email = "danijel.jakovac10@gmail.com",
                            FirstName = "Danijel - 10",
                            LastName = "Jakovac - 10",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel10"
                        },
                        new
                        {
                            Id = new Guid("de11cabe-c85b-4f11-bb64-36491b753769"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9696),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9696),
                            Email = "danijel.jakovac11@gmail.com",
                            FirstName = "Danijel - 11",
                            LastName = "Jakovac - 11",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel11"
                        },
                        new
                        {
                            Id = new Guid("bef7064b-cd97-413f-9608-10b590c30115"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9702),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9702),
                            Email = "danijel.jakovac12@gmail.com",
                            FirstName = "Danijel - 12",
                            LastName = "Jakovac - 12",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel12"
                        },
                        new
                        {
                            Id = new Guid("73d1644a-29e9-4312-b66a-5a4ad3b807ce"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9708),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9709),
                            Email = "danijel.jakovac13@gmail.com",
                            FirstName = "Danijel - 13",
                            LastName = "Jakovac - 13",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel13"
                        },
                        new
                        {
                            Id = new Guid("c62de030-942f-47ec-a263-4fe39749961d"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9714),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9715),
                            Email = "danijel.jakovac14@gmail.com",
                            FirstName = "Danijel - 14",
                            LastName = "Jakovac - 14",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel14"
                        },
                        new
                        {
                            Id = new Guid("d2299741-0b59-4e29-956f-a945927403dc"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9720),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9720),
                            Email = "danijel.jakovac15@gmail.com",
                            FirstName = "Danijel - 15",
                            LastName = "Jakovac - 15",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel15"
                        },
                        new
                        {
                            Id = new Guid("1cf70561-7f91-4d88-80cf-cd6f52da6033"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9727),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9727),
                            Email = "danijel.jakovac16@gmail.com",
                            FirstName = "Danijel - 16",
                            LastName = "Jakovac - 16",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel16"
                        },
                        new
                        {
                            Id = new Guid("c5b66ea3-1775-4181-907a-54d0c5c51e79"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9734),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9734),
                            Email = "danijel.jakovac17@gmail.com",
                            FirstName = "Danijel - 17",
                            LastName = "Jakovac - 17",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel17"
                        },
                        new
                        {
                            Id = new Guid("5d11ee27-e156-44bd-a0bd-7446fe46fccb"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9740),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9741),
                            Email = "danijel.jakovac18@gmail.com",
                            FirstName = "Danijel - 18",
                            LastName = "Jakovac - 18",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel18"
                        },
                        new
                        {
                            Id = new Guid("4cc87730-7807-4c12-9597-e34b2f4ed617"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9746),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9746),
                            Email = "danijel.jakovac19@gmail.com",
                            FirstName = "Danijel - 19",
                            LastName = "Jakovac - 19",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel19"
                        },
                        new
                        {
                            Id = new Guid("ec4d8faa-d15f-4815-a5ce-cbc79dcb919b"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9772),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9772),
                            Email = "danijel.jakovac20@gmail.com",
                            FirstName = "Danijel - 20",
                            LastName = "Jakovac - 20",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel20"
                        },
                        new
                        {
                            Id = new Guid("e8dcdcf9-770d-42be-b1c8-3396e33cd517"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9779),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9779),
                            Email = "danijel.jakovac21@gmail.com",
                            FirstName = "Danijel - 21",
                            LastName = "Jakovac - 21",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel21"
                        },
                        new
                        {
                            Id = new Guid("f83e1a89-041e-43d7-bf45-3d18b8372831"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9785),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9786),
                            Email = "danijel.jakovac22@gmail.com",
                            FirstName = "Danijel - 22",
                            LastName = "Jakovac - 22",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel22"
                        },
                        new
                        {
                            Id = new Guid("051c705a-6d66-42a9-8a34-d958a683f5a2"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9791),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9792),
                            Email = "danijel.jakovac23@gmail.com",
                            FirstName = "Danijel - 23",
                            LastName = "Jakovac - 23",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel23"
                        },
                        new
                        {
                            Id = new Guid("58d87839-bbe6-4957-a271-d5e7f5ac6027"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9799),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9800),
                            Email = "danijel.jakovac24@gmail.com",
                            FirstName = "Danijel - 24",
                            LastName = "Jakovac - 24",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel24"
                        },
                        new
                        {
                            Id = new Guid("dec336e1-4067-4828-b9eb-b1c8aded8d99"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9806),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9806),
                            Email = "danijel.jakovac25@gmail.com",
                            FirstName = "Danijel - 25",
                            LastName = "Jakovac - 25",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel25"
                        },
                        new
                        {
                            Id = new Guid("07ef98a0-bde6-4c7b-9886-026066b52610"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9812),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9812),
                            Email = "danijel.jakovac26@gmail.com",
                            FirstName = "Danijel - 26",
                            LastName = "Jakovac - 26",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel26"
                        },
                        new
                        {
                            Id = new Guid("9e3ca134-2008-4419-b8a5-4e39ac781dd6"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9817),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9818),
                            Email = "danijel.jakovac27@gmail.com",
                            FirstName = "Danijel - 27",
                            LastName = "Jakovac - 27",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel27"
                        },
                        new
                        {
                            Id = new Guid("bbfc9964-ccc5-435b-a77a-1742b9393f62"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9823),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9823),
                            Email = "danijel.jakovac28@gmail.com",
                            FirstName = "Danijel - 28",
                            LastName = "Jakovac - 28",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel28"
                        },
                        new
                        {
                            Id = new Guid("081d8f14-6ade-423a-87cc-4c91d2159c28"),
                            DateCreated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9829),
                            DateUpdated = new DateTime(2023, 2, 26, 19, 32, 47, 160, DateTimeKind.Utc).AddTicks(9829),
                            Email = "danijel.jakovac29@gmail.com",
                            FirstName = "Danijel - 29",
                            LastName = "Jakovac - 29",
                            Password = "danijel123",
                            RoleId = new Guid("d9f2cf76-cbb4-4191-9d14-3340416204ea"),
                            Username = "Danijel29"
                        });
                });

            modelBuilder.Entity("Forum.DAL.Entity.CommentEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.PostEntity", "Post")
                        .WithMany("Comment")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forum.DAL.Entity.UserEntity", "User")
                        .WithMany("Comment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.PostEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.UserEntity", "User")
                        .WithMany("Post")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.ReactionTypeEntity", "ReactionType")
                        .WithMany("Reaction")
                        .HasForeignKey("ReactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReactionType");
                });

            modelBuilder.Entity("Forum.DAL.Entity.UserEntity", b =>
                {
                    b.HasOne("Forum.DAL.Entity.RoleEntity", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Forum.DAL.Entity.PostEntity", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Forum.DAL.Entity.ReactionTypeEntity", b =>
                {
                    b.Navigation("Reaction");
                });

            modelBuilder.Entity("Forum.DAL.Entity.RoleEntity", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum.DAL.Entity.UserEntity", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
